# Generated by Django 4.2 on 2023-04-21 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='studentmodel',
        ),
    ]
