# Generated by Django 4.2 on 2023-04-21 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='studentmodel',
        ),
    ]
