# Generated by Django 4.2 on 2023-04-21 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0009_remove_studentmodel_percentage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='studentmodel',
        ),
    ]
